stages:
  data_ingestion:
    cmd: python src/Chest_Cancer_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Chest_Cancer_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest_Cancer_Images


  prepare_base_model:
    cmd: python src/Chest_Cancer_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Chest_Cancer_Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  model_training:
    cmd: python src/Chest_Cancer_Classifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/Chest_Cancer_Classifier/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest_Cancer_Images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5